### ISSUE TITLE
Ensure Node works out of the box with the ES modules compiler

### ISSUE THREAD

**Issue by thomashoneyman** [working-group-purescript-es/challenges#2]
In https://github.com/purescript/purescript/issues/4226 I proposed that we remove the PureScript bundler. However, to remove the bundler we need to prove that we can run PureScript projects on Node without requiring any additional tooling -- just PureScript and Spago should do it.

We need to create a template project or otherwise demonstrate that Node works out-of-the-box with the ES modules version of the PureScript compiler. Ideally this project would demonstrate that the compiler can be used to compile and execute the result of:

* 100% PureScript code
* PureScript code with ES modules FFI
* PureScript code with ES modules FFI that imports CommonJS FFI

**Comment by sigma-andex** [comment]
I have created example projects for this in [`node-challenge`](https://github.com/working-group-purescript-es/challenges/blob/main/node-challenge/).

I think `spago run` should generate the `index.mjs`, but apart from that I think everything is working already, or am I missing something?

**Comment by thomashoneyman** [comment]
This looks great! I believe `spago run` can execute without needing to generate any files, too.

**Comment by JordanMartinez** [comment]
Yeah, `spago run` doesn't need to generate an `.mjs` file. See https://github.com/JordanMartinez/ps-es-playground/tree/master/spago-run
