### ISSUE TITLE
Create an example project using the ES modules compiler

### ISSUE THREAD

**Issue by thomashoneyman** [working-group-purescript-es/challenges#3]
If we drop the PureScript bundler as proposed in https://github.com/purescript/purescript/issues/4226, then users who don't wish to use tooling beyond `purs` and `spago` will be using unbundled development. Before we commit to this path forward for our users, we need to be sure that development with only these tools can be ergonomic.

We can only truly test this with projects that don't require bundling in the first place (ie. PureScript-only projects). For that reason, I recommend that we fork projects like:

- https://github.com/purescript-halogen/purescript-halogen-template
- https://github.com/and-pete/purescript-halogen-template-extended

and replace the tooling there with only `purs`, `spago`, and any other PureScript-specific tooling we want like `psa` or `purs-tidy`. We can then experience what development would feel like in a PureScript browser-based project.

These templates may end up using a bundler like `esbuild` or an unbundled dev tool like `snowpack` in the future as a best practice, but we still need to test them without those tools in the first place.

**Comment by sigma-andex** [comment]
Here are the two examples. 
In the second example I have replaced the bundle process with a simple **copy everything to `prod/` and run `http-server` with this folder** strategy. This works without bundler. If this is what you aim for then I can do the same for `purescript-halogen-template`.

* [purescript-halogen-template](https://github.com/working-group-purescript-es/purescript-halogen-template/pull/1)
* [purescript-halogen-template-extended](https://github.com/working-group-purescript-es/purescript-halogen-template-extended/pull/1)

**Comment by thomashoneyman** [comment]
Fantastic! Thanks!
