### ISSUE TITLE
Understand which purity annotations to enable

### ISSUE THREAD

**Issue by thomashoneyman** [working-group-purescript-es/challenges#4]
The ES modules compiler emits `PURE` annotations, which are [a convention to help bundlers cache or remove functions without side effects](https://esbuild.github.io/api/#pure). We don't yet have a principled understanding of where these annotations are having an effect and where they're just noise.

The compiler team is unlikely to accept compiler-generated annotations that are meant for external tooling but aren't motivated by data proving they have an effect. This is especially true because these annotations are, strictly speaking, outside the domain of the compiler; the compiler team is never going to chase after a goal of optimizing for bundlers, but we can at least do some common-sense annotations that are proven to work.

This issue tracks producing a table or other evidence that specific annotations have a desirable effect on bundle sizes and generated code. We should apply the scientific method here:

1. We should settle on a selection of examples for comparison's sake: perhaps the Halogen template, Real World Halogen, and Real World PureScript React. For a specific annotation we should also have a specific 'hello world' example that isolates the effect of that annotation alone -- for example, if the annotation is on data constructors, then we should have an example that has just data constructors so we can see the effect.
2. We should settle on a selection of bundlers to test (for example: webpack, parcel, and esbuild) just in case they handle things differently.
3. We should determine where purity annotations are likely to have an effect -- for example: data type declarations, type class constructors), and list them out as things to test
4. We should build the examples with the compiler and no annotations and see what the resulting bundles look like. This is our comparison case.
5. For each proposed annotation, we should build all the examples again using a compiler with only that annotation enabled, and then check the resulting bundle sizes. Did the annotation have an effect?

With these results, we can put together a table listing each of the annotations we tested and what effect it had, and propose that to the compiler team as the set of annotations to include in compiler output.

**Comment by sigma-andex** [comment]
I have added a section [bundle-challenge](https://github.com/working-group-purescript-es/challenges/tree/main/bundle-challenge#bundle-challenge) and evaluated `purescript-halogen-template` with different bundlers and configs. 

I bundled with the current purity annotations, with a version only using purity annotations for constructors and without purity annotations. The result can be seen [here](https://github.com/working-group-purescript-es/challenges/tree/main/bundle-challenge#results)

**Comment by thomashoneyman** [comment]
This has been resolved by the work in https://github.com/working-group-purescript-es/purescript/pull/7. There's no table of annotations, but the implementation is simple and not upstream of optimizations.
