### ISSUE TITLE
Evaluate tooling for our official ES modules recommendation

### ISSUE THREAD

**Issue by thomashoneyman** [working-group-purescript-es/challenges#5]
In https://github.com/purescript/purescript/issues/4226 I proposed we remove the PureScript bundler. If we do, then we need to recommend a path forward for users of `purs bundle` and `spago bundle`. This decision will be reflected in the PureScript documentation and the PureScript 0.15 migration guide.

We need to recommend tooling for users and write a transition guide if you were previously using just `purs bundle` / `spago bundle`. The tooling we recommend should be:

* Stable (we shouldn't recommend experimental software to our users)
* As fast as `purs bundle`
* As effective as `purs bundle` (in terms of bundle size)

After #3 -- or in parallel with it -- we could use any options we're curious about in those templates to see how they perform. Here are some options that I have heard floated as an official PureScript recommendation:

* [`esbuild`](https://esbuild.github.io) -- which isn't yet at 1.0.0, but [is stable](https://esbuild.github.io/faq/#production-readiness) and has static binaries that don't require users to install a Node runtime
* [`webpack`](https://webpack.js.org) -- which is certainly stable and used practically everywhere, but is written in JS and tends to be slow
* [`parcel`](https://parceljs.org) -- which is similar to Webpack, but has recently been rewritten in Rust. Unfortunately, I've encountered bugs with it trying to migrate at work and with Real World Halogen

There are also more sophisticated options we could recommend:
* [`snowpack`](https://www.snowpack.dev) -- a tool supporting unbundled development, only bundling when it comes to the production build. It uses `esbuild` as its built-in bundler.

This issue tracks three tasks:

- [ ] Evaluate tooling for use as the official PureScript recommendation
- [ ] Create a Discourse poll with the tools that seem like reasonable options for the community so the community can respond
- [ ] Write a short transition guide for users of `purs bundle` and `spago bundle` for how they would start bundling with another tool.

**Comment by thomashoneyman** [comment]
My bias is probably clear from my writing above, but I think `esbuild` is a fantastic, do-one-thing bundler. It's close enough to stable for my taste, and the fact that other popular tools rely on it by default (`snowpack`, for example) is evidence of that.

I am really curious about `snowpack` as an option, but I tend to like the smaller, slower-changing projects as a default recommendation so that we don't have to keep pace with changes as much. Users are free to use whatever they want, after all.

So my vote is `esbuild`, but I'm curious about what other options there are out there and what everyone else thinks.

**Comment by sigma-andex** [comment]
I have added a section [bundle-challenge](https://github.com/working-group-purescript-es/challenges/tree/main/bundle-challenge#bundle-challenge) and evaluated `purescript-halogen-template` with different bundlers and configs.

**Comment by sigma-andex** [comment]
*Note:* purs-none should be pure-none in the images below
<img width="628" alt="Screenshot 2022-01-24 at 20 26 58" src="https://user-images.githubusercontent.com/77549848/150859421-1b2b93bc-42b1-4a59-a42d-c0bde48f8440.png">
<img width="629" alt="Screenshot 2022-01-24 at 20 27 09" src="https://user-images.githubusercontent.com/77549848/150859427-e4a3a03c-2ef1-4b0d-bf8e-96b10b19eb2e.png">

**Comment by sigma-andex** [comment]
some findings:
- bundles using constructor-only purity annotations are roughly 40-50% bigger than purs-bundle + js bundler
- adding purity annotations more aggressively (pure-all) gets equal or even better bundle sizes than purs bundle + js bundler
- webpack does the best job in minifying
- webpack minified (+ gz) and pure-ctors are almost the same as purs bundle => adding some more purity annotation will probably lead to better bundle sizes than purs bundle+js bundler
- when compared to plain purs bundle (i.e. without additional bundler), the other bundlers are already creating smaller bundles (50-60% bundle size in comparison to purs bundle) with minimal purity annotations and even without any purity annotations

**Comment by natefaubion** [comment]
To be clear, pure-ctors is only annotating inlined constructor _applications_. It is not annotating the constructor declarations. I think we need to annotate the declarations as well.

**Comment by sigma-andex** [comment]
For completion using @natefaubion 's top-level annotations:

```
➜ exa -lah --no-user --no-time --no-permissions -R bundles/*/pure-top-level                 
bundles/esbuild/pure-top-level:
Size Name
204k index.js
 85k index.minified.js

bundles/parcel/pure-top-level:
Size Name
2.1M index.1b5c3bd2.js
 80k index.f5495ba4.js
 166 index.html

bundles/webpack/pure-top-level:
Size Name
3.0M index.js
 78k index.minified.js
(base) 
```

**Comment by sigma-andex** [comment]
> So my vote is `esbuild`, but I'm curious about what other options there are out there and what everyone else thinks.

@thomashoneyman my vote also goes to `esbuild` for the following reasons:
- with Nate's top-level purity annotations the bundlers don't differ much in minified bundle size and are much better than the current purs-bundle
- `esbuild` outperforms the other bundlers when producing a *readable* bundle 
- `esbuild` is a standalone tool that doesn't require npm or node
- `esbuild` doesn't require a config in comparison to `webpack`
- `esbuild` is way faster than the others, e.g. 
    - bundle: 
      - esbuild 38ms
      - parcel 112ms
      - webpack 601ms
    - minified bundle: 
      - esbuild 36ms
      - parcel 2090ms
      - webpack 3027ms

I haven't considered:
- `snowpack`: because it internally uses `esbuild` anyway and is more of a high-level tool 
- `rollup.js`: seems a bit outdated and is written in js/ts, so probably rather slow
- `browserify`:  outdated
