### ISSUE TITLE
Collect guidance for migrating FFI modules in PureScript 0.15

### ISSUE THREAD

**Issue by thomashoneyman** [working-group-purescript-es/challenges#6]
We should collect advice, tools, and anything else that will help users migrate their FFI modules from being written in CommonJS to being written in ES modules.

I believe that VSCode has built-in support for automatically migrating them -- if anyone knows how this is done and whether we could get access to it as a standalone tool, that could be a huge help.

Otherwise, feel free to use this thread to collect anything we learn along the way while upgrading all core, node, web, and contrib libraries to use ES modules in FFI!

Related: #1

**Comment by i-am-the-slime** [comment]
Here's a gif for the VScode version. https://umaar.com/dev-tips/222-vs-code-convert-es-import/

Other than that, I've found this script (I couldn't find out what vscode uses under its hood):
~https://umaar.com/dev-tips/222-vs-code-convert-es-import/~ (Edit: wrong link)
 https://github.com/nolanlawson/cjs-to-es6

**Comment by thomashoneyman** [comment]
It looks like those are both the same link — is the second one meant to be different?

**Comment by i-am-the-slime** [comment]
@thomashoneyman Yes, sorry I meant this: https://github.com/nolanlawson/cjs-to-es6

**Comment by i-am-the-slime** [comment]
Here's a thing that's been cropping up:

**It seems quite important to point to the actual `.js` file in imports**
Webpack 5 likes saying this:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'vanta/dist/vanta.birds.min' in '/Users/mark/code/swarm/app/murmuras-insights/output/React.Vanta.Birds'
Did you mean 'vanta.birds.min.js'?
BREAKING CHANGE: The request 'vanta/dist/vanta.birds.min' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
```

We should include this tip in our guidance.

**Comment by i-am-the-slime** [comment]
@natefaubion mentioned this one: https://github.com/wessberg/cjstoesm

**Comment by sigma-andex** [comment]
`cjstoesm "src/**/*.js" esm/ && cp -f -R esm/ . && rm -rf esm/`

**Comment by natefaubion** [comment]
`lebab` also does this (for some forms, and doesn't require `typescript` to be installed). I had trouble with both tools on our work codebase for various reasons, however.

**Comment by nwolverson** [comment]
The vscode conversion that was mentioned above is from the TypeScript language service, seems to be here for reference https://github.com/microsoft/TypeScript/blob/main/src/services/codefixes/convertToEsModule.ts (that doesn't look very standalone)
