### ISSUE TITLE
Create a new error for CJS modules

### ISSUE THREAD

**Issue by thomashoneyman** [working-group-purescript-es/challenges#7]
We need to create a new error in the PureScript documentation for when we detect a CJS module (see https://github.com/purescript/documentation/blob/master/errors/CycleInDeclaration.md for an example).

This error should include guidance on how to migrate your code from CJS to ES modules -- work that's being done in #6 and in this Discourse post:

https://discourse.purescript.org/t/call-for-participation-help-es-modules-team-test-migration-tools

Ultimately that will end up in the migration guide for the compiler and the CJS error can link over to the migration guide. But we still need the CJS error to specify that the compiler does not accept CJS modules anymore and you need to migrate to ES modules.

**Comment by sigma-andex** [comment]
There is already `DeprecatedFFICommonJSModule`, currently emitting (in my branch):
```
[1/1 DeprecatedFFICommonJSModule] src/Main.purs:1:1

      v
   1  module Main where
   2  
   3  import Prelude
      ...
  10  main :: Effect Unit
  11  main = do
  12      log hello
                  ^
  
  A CommonJS foreign module implementation was provided for module Main:
  
    src/Main.js
  
  CommonJS foreign modules are deprecated and won't be supported in the future.

           Src   Lib   All
Warnings   0     0     0  
Errors     1     0     1  
[error] Failed to build.
```
